services:
  terraform:
    build: .
    container_name: terraform
    working_dir: /workspace
    volumes:
      - ./src:/workspace                    # Mount current project dir
      - ~/.aws:/root/.aws
      # - ~/.aws/sso:/root/.aws/sso:ro      # THIS IS CRITICAL
    environment:
      - AWS_REGION=eu-north-1
    # entrypoint: ["terraform"]
